# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mypnorm <- function(x, mu, sigma) {
    .Call('_stpdpm_mypnorm', PACKAGE = 'stpdpm', x, mu, sigma)
}

calc_distC <- function(X, Y) {
    .Call('_stpdpm_calc_distC', PACKAGE = 'stpdpm', X, Y)
}

calc_dist_selfC <- function(X) {
    .Call('_stpdpm_calc_dist_selfC', PACKAGE = 'stpdpm', X)
}

edistC <- function(x, y) {
    .Call('_stpdpm_edistC', PACKAGE = 'stpdpm', x, y)
}

gauss_kernelC <- function(x, y, theta = 1.0) {
    .Call('_stpdpm_gauss_kernelC', PACKAGE = 'stpdpm', x, y, theta)
}

gauss_kernel_gramC <- function(X, theta = 1.0) {
    .Call('_stpdpm_gauss_kernel_gramC', PACKAGE = 'stpdpm', X, theta)
}

decorrelateC <- function(Z, Sigma) {
    .Call('_stpdpm_decorrelateC', PACKAGE = 'stpdpm', Z, Sigma)
}

cholC <- function(Sigma) {
    .Call('_stpdpm_cholC', PACKAGE = 'stpdpm', Sigma)
}

solveC <- function(Sigma) {
    .Call('_stpdpm_solveC', PACKAGE = 'stpdpm', Sigma)
}

myqnorm <- function(x, mu, sigma) {
    .Call('_stpdpm_myqnorm', PACKAGE = 'stpdpm', x, mu, sigma)
}

rtmvtnormC <- function(n, mean, H, lower, upper, init, burn_in_samples = 0L, thinning = 1L, initialize_x0 = FALSE) {
    .Call('_stpdpm_rtmvtnormC', PACKAGE = 'stpdpm', n, mean, H, lower, upper, init, burn_in_samples, thinning, initialize_x0)
}

